### ISSUE TITLE
Navbar link arrangement breaks on mobile

### ISSUE THREAD

**Issue by kforney** [CarsonStrout/carsonstrout.github.io#2]
When viewed on mobile, the navbar links get broken into two rows. I would suggest collapsing the navbar into a single-column menu on mobile instead.

![Screenshot from 2023-02-07 18-51-59](https://user-images.githubusercontent.com/5742001/217408356-182926e6-e4e9-4163-8dd7-d7867bb6b25d.png)

**Comment by CarsonStrout** [comment]
Fixed
